// <auto-generated />
namespace LearnerDictionary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addIsLearning : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addIsLearning));
        
        string IMigrationMetadata.Id
        {
            get { return "201707021100580_addIsLearning"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
